org: thiagorm
service: diagram-studio-api

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 29
  iam:
    role: arn:aws:iam::264641143307:role/LabRole
  environment:
    USERS_TABLE_NAME: t_usuarios_UD
    TOKENS_TABLE_NAME: t_tokens_acceso
    BUCKET_NAME: diagram-studio-storage
  httpApi:
    cors:
      allowedOrigins:
        - '*'
      allowedMethods:
        - GET
        - POST
        - OPTIONS
      allowedHeaders:
        - Content-Type
        - Authorization

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  RegistarUsuarioUD:
    handler: register.lambda_handler
    events:
      - httpApi:
          path: /auth/register
          method: POST

  LoginUsuarioUD:
    handler: login.lambda_handler
    events:
      - httpApi:
          path: /auth/login
          method: POST

  generar_diagrama:
    handler: generar_diagrama.lambda_handler
    events:
      - httpApi:
          path: /diagrams/generate
          method: POST

  descargar_diagrama:
    handler: descargar_diagrama.lambda_handler
    events:
      - httpApi:
          path: /diagrams/download
          method: POST

resources:
  Resources:
    TablaUsuarios:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: usuario_id
            AttributeType: S
        KeySchema:
          - AttributeName: usuario_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    TablaTokens:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TOKENS_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: token
            AttributeType: S
        KeySchema:
          - AttributeName: token
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    DiagramsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET_NAME}
